# Generated by Django 4.2.9 on 2024-02-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
