# Generated by Django 4.2.9 on 2024-02-06 20:26

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='templates/assets/images/user-temp.png', upload_to='profiles/'),
        ),
    ]
