# Generated by Django 4.2.9 on 2024-01-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_published', models.DateField()),
                ('category', models.IntegerField(choices=[(0, ''), (1, 'Sweater'), (2, 'Cardigan'), (3, 'Skirt'), (4, 'Pants'), (5, 'Hat'), (6, 'Scarf')], default=0)),
                ('weight', models.IntegerField(choices=[(0, 'Cobweb'), (1, 'Lace'), (2, 'Fingering'), (3, 'DK'), (4, 'Worsted')], default=0)),
                ('needle', models.IntegerField(choices=[(0, '1mm'), (1, '2mm'), (2, '3mm'), (3, '4mm')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
