# Generated by Django 4.2.9 on 2024-01-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_pattern_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='slug',
        ),
    ]
