# Generated by Django 4.2.9 on 2024-01-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_remove_pattern_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='first_published',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='needle',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='weight',
        ),
    ]
