# Generated by Django 4.2.9 on 2024-01-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0004_remove_pattern_author_remove_pattern_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
