# Generated by Django 4.2.9 on 2024-01-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0008_pattern_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='needle',
            field=models.IntegerField(choices=[(0, '1mm'), (1, '2mm'), (2, '3mm'), (3, '4mm')], default=0),
        ),
        migrations.AddField(
            model_name='pattern',
            name='weight',
            field=models.IntegerField(choices=[(0, 'Cobweb'), (1, 'Lace'), (2, 'Fingering'), (3, 'DK'), (4, 'Worsted')], default=0),
        ),
    ]
