# Generated by Django 4.2.9 on 2024-01-30 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0009_pattern_needle_pattern_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
