# Generated by Django 4.2.9 on 2024-01-30 21:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0010_pattern_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='pattern/'),
        ),
    ]
