# Generated by Django 4.2.9 on 2024-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0012_alter_pattern_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_pdf',
            field=models.FileField(default=1, upload_to='patterns/'),
            preserve_default=False,
        ),
    ]
