# Generated by Django 4.2.9 on 2024-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0013_pattern_pattern_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='pattern_pdf',
        ),
        migrations.AddField(
            model_name='pattern',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
