# Generated by Django 4.2.9 on 2024-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0014_remove_pattern_pattern_pdf_pattern_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='link_pattern',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
